### ISSUE TITLE
Error on Timeout

### ISSUE THREAD

**Issue by tfang17** [amplitude/Amplitude-Node#101]
## Expected Behavior
Unexpected error on Timeout when calling Amplitude logEvent.

## Current Behavior
```Error
    at Timeout._onTimeout (/workspace/node_modules/@amplitude/utils/dist/src/queue.js:67:48)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) ```

## Possible Solution
Didn't happen in previous SDKs. Looks like there were some recent code changes to that queue.js file.

## Steps to Reproduce
Happens occasionally on calls to logEvent.

## Environment
- SDK Version: 1.5.3
- Node version: 10

**Comment by axelvaindal** [comment]
I have the same bug and it affects approximately 25% of my logs at high scale.
I'll rollback to a previous version to see if it helps

**Comment by tfang17** [comment]
Bug is only in new version. Temp fix is to roll back to older version.

**Comment by ajhorst** [comment]
@tfang17 we released v1.5.4 earlier this week with fixes to the timeout logic. When you have a chance, upgrade to that version and let me know if you're still seeing timeout issues
