### ISSUE TITLE
Cannot flush if no prior logEvent invocations

### ISSUE THREAD

**Issue by tommedema** [amplitude/Amplitude-Node#85]
When you call amplitude.flush without previously calling amplitude.logEvent (which is common if you iterate over a list of events and it just so happens that the list of events is empty), the library will throw with:

```
ERROR	Invoke Error 	
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'length' of undefined",
    "stack": [
        "TypeError: Cannot read property 'length' of undefined",
        "    at Object.<anonymous> (/var/task/node_modules/@amplitude/node/dist/src/nodeClient.js:51:42)",
        "    at step (/var/task/node_modules/tslib/tslib.js:139:27)",
        "    at Object.next (/var/task/node_modules/tslib/tslib.js:120:57)",
        "    at /var/task/node_modules/tslib/tslib.js:113:75",
        "    at new Promise (<anonymous>)",
        "    at Object.__awaiter (/var/task/node_modules/tslib/tslib.js:109:16)",
        "    at Object.NodeClient.flush [as flushAmplitude] (/var/task/node_modules/@amplitude/node/dist/src/nodeClient.js:40:24)",
        "    at Runtime.exports.eventBusTrackingFanout [as handler] (/var/task/dist/eventsProcessor.js:28:23)"
    ]
}
```

**Comment by tommedema** [comment]
This is the line that throws: https://github.com/amplitude/Amplitude-Node/blob/0fb26cefb4527c84ec6ac4f805ae1fb0f91efc09/packages/node/src/nodeClient.ts#L55
