### ISSUE TITLE
TypeError: Cannot read property 'length' of null (retryHandler.ts:102:18)

### ISSUE THREAD

**Issue by IsaiahJTurner** [amplitude/Amplitude-Node#99]
This error is crashing our server unrecoverabley and forcing us to replace the entire instance whenever it happens:
Hoping an urgent fix or info on how to avoid is available!

```
Unhandled rejection in index.js TypeError: Cannot read property 'length' of null
Apr 02 21:06:36     at /var/app/current/node_modules/@amplitude/node/src/retryHandler.ts:102:18
Apr 02 21:06:36     at Array.forEach (<anonymous>)
Apr 02 21:06:36     at RetryHandler._pruneEvents (/var/app/current/node_modules/@amplitude/node/src/retryHandler.ts:99:12)
Apr 02 21:06:36     at RetryHandler.<anonymous> (/var/app/current/node_modules/@amplitude/node/src/retryHandler.ts:61:31)
Apr 02 21:06:36     at step (/var/app/current/node_modules/tslib/tslib.js:141:27)
Apr 02 21:06:36     at Object.next (/var/app/current/node_modules/tslib/tslib.js:122:57)
Apr 02 21:06:36     at /var/app/current/node_modules/tslib/tslib.js:115:75
Apr 02 21:06:36     at new Promise (<anonymous>)
Apr 02 21:06:36     at Object.__awaiter (/var/app/current/node_modules/tslib/tslib.js:111:16)
```

**Comment by kelvin-lu** [comment]
@IsaiahJTurner we'll be taking a look! and ensuring at the very least that this is not causing uncontrollable errors
